# Generated by Django 4.1.7 on 2023-03-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trends',
            },
        ),
    ]
